[build]
builder = "NIXPACKS"

[build.nixpacks]
pkgs = ["python310", "python310Packages.pip"]

[deploy]
startCommand = "python3 api-server.py"
healthcheckPath = "/api/stats"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"