[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "python3 -m pip install -r requirements.txt"
]

[start]
cmd = "bash start.sh"

[build]
builder = "NIXPACKS"
buildCommand = "python3 -m pip install -r requirements.txt"

[deploy]
startCommand = "bash start.sh"
healthcheckPath = "/api/stats"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[[services]]
name = "api"
startCommand = "python3 api-server.py"

[[services]]
name = "agent"
startCommand = "python3 agent/core/agent.py"
